//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Halı_Saha_Yönetim
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_odeme
    {
        public int ODEME_ID { get; set; }
        public Nullable<int> ODEME_REZ_ID { get; set; }
        public Nullable<int> ODEME_SAHA_ID { get; set; }
        public Nullable<bool> DURUM { get; set; }
        public Nullable<decimal> ODEME_UCRET { get; set; }
    
        public virtual tbl_rezervasyon tbl_rezervasyon { get; set; }
        public virtual tbl_saha tbl_saha { get; set; }
    }
}
